# This is a basic workflow to help you get started with Actions

name: CRDA-CI-Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  REPOSITORY: fabric8-analytics-server
  DEFAULT_TAG: latest
  FULL_NAME: bayesian-bayesian-api
  TESTS_IMAGE: server-tests
  ORGANIZATION: practice-fabric8-analytics

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
         python-version: 3.6
      # Runs a set of commands using the runners shell
      - name: Setup tests 
        run: |
          pip install -U pip;
          pip install virtualenv;
          virtualenv --version;
          ls;
          virtualenv -p python3 venv && source venv/bin/activate;
          ls;
          pip install -r tests/requirements.txt;
          ls;
          echo pwd;
          PYTHONPATH=`pwd` python3 "$(which pytest)" --cov=f8a_utils/ --cov-report term-missing --cov-fail-under=95 -vv tests/;
          codecov --token=b3420bb6-159c-49d3-8bd2-9cf2727069e8;
      - name: Upload Code coverage
        uses: codecov/codecov-action@v1 
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: coverage.xml # optional
      
          
          
          
    
