name: CRDA Python Linter and Docstyle (matrix based)

on:
  pull_request:
    branches: [ master ]
    
jobs:
  build:
   

    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts: [run-linter, check-docstyle, detect-common-errors, detect-dead-code, measure-cyclomatic-complexity, measure-maintainability-index]
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run ${{matrix.scripts}}
      run: bash qa/${{matrix.scripts}}.sh;
